apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: inventory-quarkus-end-to-end-developer-workshop-1hak
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: inventory-quarkus-end-to-end-developer-workshop-1hak
    app.kubernetes.io/part-of: end-to-end-labs2
  name: inventory-quarkus-end-to-zmcz
  namespace: agroom-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: inventory-quarkus-end-to-end-developer-workshop-1hak
    weight: 100
status: {}
