apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: inventory-quarkus-end-to-end-developer-workshop-1hak
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: inventory-quarkus-end-to-end-developer-workshop-1hak
    app.kubernetes.io/part-of: end-to-end-labs2
  name: inventory-quarkus-end-to-end-developer-workshop-1hak
  namespace: agroom-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: inventory-quarkus-end-to-end-developer-workshop-1hak
status:
  loadBalancer: {}
