apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: catalog-spring-boot-end-to-end-developer-workshop-z4fn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: catalog-spring-boot-end-to-end-developer-workshop-z4fn
    app.kubernetes.io/part-of: end-to-end-labs2
  name: catalog-spring-boot-end-to-end-developer-workshop-z4fn
  namespace: agroom-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: catalog-spring-boot-end-to-end-developer-workshop-z4fn
status:
  loadBalancer: {}
