apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gateway-dotnet-end-to-end-developer-workshop-hxv1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gateway-dotnet-end-to-end-developer-workshop-hxv1
    app.kubernetes.io/part-of: end-to-end-labs2
  name: gateway-dotnet-end-to-endrcap
  namespace: agroom-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gateway-dotnet-end-to-end-developer-workshop-hxv1
    weight: 100
status: {}
