apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gateway-dotnet-end-to-end-developer-workshop-hxv1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gateway-dotnet-end-to-end-developer-workshop-hxv1
    app.kubernetes.io/part-of: end-to-end-labs2
  name: gateway-dotnet-end-to-end-developer-workshop-hxv1
  namespace: agroom-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: gateway-dotnet-end-to-end-developer-workshop-hxv1
status:
  loadBalancer: {}
