apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: catalog-go-end-to-end-developer-workshop-cpyd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: catalog-go-end-to-end-developer-workshop-cpyd
    app.kubernetes.io/part-of: end-to-end-labs2
  name: catalog-go-end-to-end-developer-workshop-cpyd
  namespace: agroom-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: catalog-go-end-to-end-developer-workshop-cpyd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: catalog-go-end-to-end-developer-workshop-cpyd
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:ZzBzx-catalog-go-end-to-end-developer-workshop-cpyd
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
